### ISSUE TITLE
Srf#createB2BUA with ws/wss endpoints

### ISSUE THREAD

**Issue by andrewvmail** [davehorton/drachtio-srf#10]
Hi Dave, 

I can't seem to connect 2 ws/wss endpoints together. I keep getting 503 error. Both my UA were able to register fine. Can send invite fine but the createB2BUA errors out. My feeling is I'm not correctly giving it the correct uri parameter. I can get this to work with a non ws. 

I have tried using these for the uri
``` sip:user@serverip;transport=ws ```
``` sip:user@serverip;transport=wss ```
``` sip:5u3qdt9g@rcrfaf1aghbt.invalid;transport=ws ```
``` sip:5u3qdt9g@rcrfaf1aghbt.invalid;transport=wss ```
``` sip:<receiver>:<rport>; transport=ws ```
``` sip:<receiver>:<rport>; transport=wss ```

Thanks in advance

**Comment by davehorton** [comment]
I will look into it.  So basically the scenario is two endpoints each register over wss (or ws) and then one calls the other?

**Comment by andrewvmail** [comment]
Found more stuff might be useful or interesting

If you register one UA and you call your self it works. 

Alink to the websocket sip spec https://tools.ietf.org/id/draft-ietf-sipcore-sip-websocket-01.html#implementation_guidelines_client that might explain browser vendors implementation for the weird looking uri on the webrtc stack

**Comment by davehorton** [comment]
Hmm, I am testing on my own server and using https://github.com/davehorton/simple-drachtio-registrar and I am able to connect, register, and then place a call between the two.

Can you verify my results so I can understand the difference between our setups?  You can use `wss://tighthead.drachtio.org:4433` as the server, and these two sets of credentials:
```
name: John Doe
sip uri: user1@drachtio.org
auth username: user1
password: pass123

name: Jane Doe
sip uri: user2@drachtio.org
auth username: user2
password: pass123
```

**Comment by andrewvmail** [comment]
👍 Yeah I can confirm your server is working!!

**Comment by andrewvmail** [comment]
Hi Dave I got it!! I got a fix. Its a race. I just need to give some time for drachtio server to process things. Just to give you some context of what I'm doing. Its a mobile to mobile app. 
- UA1 calling UA2
- UA1 sends an invite to drachtio/node then i simulate a pause of execution using setTimeout and an eventEmitter
- drachtio/node then sends a voip push through apn/gcm to UA2
- voip push wakes up UA2 device and do register
- that register emits a signal that resumes UA1 invite execution

I just put a 500ms delay just before emitting the signal that un pauses the execution. And its working now 👍 

What do you think of this 500ms delay? Is there a better approach to this?

Thanks!

**Comment by davehorton** [comment]
Ah, ok this makes sense then.  I think your solution sounds fine.  

I do know of another customer that has taken a slightly different approach. When the INVITE from UA1 comes in, they park the call (on a freeswitch server, in their case) and send a push notification to UA2, which responds by sending an INVITE to the server which connects to and unparks the first call.  (The push notification includes a parking slot id that is used in the INVITE to identify the parked call to connect to).  Its obviously a bit more complicated but eliminates any race condition is a bit more snappy in terms of connecting the call.

**Comment by andrewvmail** [comment]
Hmm this is interesting. Will keep this in mind. Haven't completely build what I have in mind yet but curious later to compare numbers on snappiness  😄 Also I'll be using coturn instead of freeswitch for media.

Closing this issue

Thanks again!
