### ISSUE TITLE
proxy on outbound request

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-srf#11]
Hi,

There was a commit on Sep 30, 2017 to support proxy for outbound requests. Does this work?

Should the srf code be like this?
`srf.request(uri, {method: 'NOTIFY', proxy: '192.168.1.21:5060'},...`

I am testing this but it doesn't seem to have an effect. I would like to send the request to an alternative location which is a SIP proxy.

Thanks,

James

**Comment by davehorton** [comment]
The comment pertained to the `Srf#createUAC` method, where you can have `opts.proxy` set to a proxy, e.g.

```js
srf.createUAC(uri, {
        proxy: anOutboundProxy,
        localSdp: anSdp
      })
```
However, what you have should work as well..are you testing with the latest version (4.2.17)?  If not can you try that?

**Comment by davehorton** [comment]
Also, the issue may be caused if you are using an older version of drachtio-server?  If you are using the docker image can you make sure to test with the `latest` tag?  If you are building your own, can you build the latest on the 'develop' branch?

You can also check the version of your docker image by doing this
```
MacBook-Pro-2:~ dhorton$ docker run -ti drachtio/drachtio-server:latest drachtio --version
v0.7.2-rc4-2-g58ab55a
```

**Comment by JimG777** [comment]
Hi Dave,

Thanks for your help again! My use case might be a bit complicated now, so maybe I can look at other ways to do it. I am not sure if there is a solution you can provide. In any case, in my situation, I have this:

UE (172.25.0.10) -> Proxy (172.25.0.5) -> Host (*.1, 192.168.1.1) -> IMS (172.29.0.4)
- UE and Proxy are in one Docker network.
- IMS is in another Docker network.
- The Host is just the common host in this case with all the Docker gateway addresses (172.25.0.1 & 172.29.0.1) and the actual public IP.

Of course, Proxy and IMS are drachtio-server. UE issues a SUBSCRIBE, it goes through Proxy, which points it to 192.168.1.1:5060, which is mapped by Docker to 172.29.0.4:5060.

I want the IMS server to issue a NOTIFY back to UE when it gets the SUBSCRIBE. I do this by making a srf.request() with the method set to NOTIFY and use the Call-ID from the SUBSCRIBE. But, it tries to send directly to 172.25.0.5 which isn't known to the 172.29.0.* subnet.

I have tried to set the outbound proxy, but it doesn't have an effect. I tried even to set the Record-Route at the Proxy to point to 192.168.1.1:65060 (this is the port it listens to) but drachtio seems to be overriding that back to 172.25.0.5.

As a workaround, I can put the IMS in the same subnet as the other entities, or, maybe I can host the IMS server on the host directly (but I prefer to keep all in Docker). At some point, I want to run the IMS part on a separate dedicated Host but still in Docker there.

I confirmed that I am using the latest version of drachtio-server. I rebuilt a few days ago from develop.

Thanks,

James

**Comment by davehorton** [comment]
OK, I see.  The SUBSCRIBE is basically being routed by a non-SIP element, so the Route set it constructs for the dialog ends up having an unreachable first hop.

Hmm..not sure I have a quick solution.  I will think about it.  

When you mentioned the Proxy is listening on 192.168.1.1:65060, I thought maybe you could use the [external-ip property](http://beta.drachtio.org/docs/drachtio-server#contacts) property to have it advertise that IP:port in its messaging -- but then I remembered that this only works with an IP address currently, not an IP and port.  Maybe that is something I need to think about adding..

**Comment by davehorton** [comment]
BTW, in case it is of interest (not that it will solve this problem, but to see other related code), I am working on simple presence agent of my own at: https://github.com/davehorton/drachtio-simple-server

**Comment by davehorton** [comment]
actually, just for yucks, I would be interested to see what happens if you assign '192.168.1.1:65060' to the external-ip property of the drachtio server running the proxy app.  If you are starting it via docker you should be able to do it via a command line argument like so:

```
docker exec drachtio/drachtio-server:latest drachtio --contact "sip:*;udp" --external-ip "192.168.1.1:65060"
```
Not sure this will work but it might.  If it does not I'd be interested to see the server logging from the proxy.

See [here](http://beta.drachtio.org/docs/drachtio-server#command-line-arguments) for details on command line arguments

**Comment by JimG777** [comment]
Hi Dave,

I will try some of the testing with the external-ip and let you know. Your drachtio-simple-server looks good, but we are focused on working with clients using MSRP IM at the moment!

I also have a few other scenarios to test and may have additional questions. For now, I am running with the IMS server in the same Docker network without a Proxy. Even without a proxy, the previous network layout didn't work:

`UE (172.25.0.10) -> Host (*.1, 192.168.1.1) -> IMS (172.29.0.4)`

The NOTIFY could not get back to the UE via the Host. If the request comes from another machine on the Host network, it works and can be routed:

`UE2 (192.168.1.10) -> Host (*.1, 192.168.1.1) -> IMS (172.29.0.4)`

I think if the IMS server is on its own Host it will work well. It just isn't convenient for testing.

Thanks!

**Comment by davehorton** [comment]
Just wondering, is there a reason you want the IMS in a completely different docker subnet?  i.e., why not use docker-compose to create a docker network and put all your containers at separate IPs in that subnet?

On May 24, 2018, at 8:04 PM, James <notifications@github.com> wrote:

Hi Dave,

I will try some of the testing with the external-ip and let you know. Your drachtio-simple-server looks good, but we are focused on working with clients using MSRP IM at the moment!

I also have a few other scenarios to test and may have additional questions. For now, I am running with the IMS server in the same Docker network without a Proxy. Even without a proxy, the previous network layout didn't work:

UE (172.25.0.10) -> Host (*.1, 192.168.1.1) -> IMS (172.29.0.4)

The NOTIFY could not get back to the UE via the Host. If the request comes from another machine on the Host network, it works and can be routed:

UE2 (192.168.1.10) -> Host (*.1, 192.168.1.1) -> IMS (172.29.0.4)

I think if the IMS server is on its own Host it will work well. It just isn't convenient for testing.

Thanks!

**Comment by JimG777** [comment]
It was mainly for testing purposes to keep the deployments separated and was trying to simulate the case with the Proxy in between. But as a workaround, I am running with the IMS server in the same Docker network without a Proxy in the middle, and it is working. I still need to bring in the Proxy, which I will do and open a new issue if there are any other issues with that flow.

I will close this issue, I think the problem is my use case not really being compatible with Docker networking.

Thanks for all the help and clarifications.
