### ISSUE TITLE
Connecting 2 softphones

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-srf#14]
Hi, I am new to drachtio, I installed drachtio-server and using drachtio-srf. I couldn't figure out how can I establish a call between 2 agents. I can register agents with softphone. Now I have to send invite message with sdp from one to other and response from other agent. When using softphone, I receive 100 Trying message server, I have to redirect the call but I couldnt find any samples.

**Comment by davehorton** [comment]
have you checked on drachtio.org?  Its kind of new, but I have docs and example apps up there.  Let me know if you are still blocked after reviewing that, and I will be happy to help!

**Comment by salihy** [comment]
I checked with no luck. What I need is very easy just start full sip and rtp conversation between 2 softphones.

Thanks

**Comment by davehorton** [comment]
ok.  I'd like to understand the call flow better, so I can help construct a working scenario.  When you say "I have to redirect the call", do you mean when softphone 1 calls softphone 2 that you want the drachtio server to send a 302 Moved back to softphone1?

Or, when receiving the INVITE from softphone 1 do you want the drachtio server to send the INVITE to softphone 2?  If so, do you want the drachtio server to act as a proxy, or as a back to back user agent?

Are these softphones going to be behind a NAT?

**Comment by davehorton** [comment]
Can you look at this app and see if it helps you at all:

https://github.com/davehorton/drachtio-b2b-media-proxy

Its not exactly all that you are looking for but it should show you the INVITE handling that seems to be the sticking point right now
