### ISSUE TITLE
B2BUA Contact Header

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-srf#15]
When implementing b2bua for Invite, an Invite comes from user A containing a Contact header with various params such as sip.instance and other feature tags. However, the b2bua send the Invite out to user B with only the sip uri, with no other params. I tried to add 'Contact' to the proxyRequestHeaders array, but it just puts in a second Contact in the SIP header. The client chokes on this, maybe it should be more flexible. But is there a way to conserve the original Contact header?

**Comment by davehorton** [comment]
You should be able to explicitly add a Contact header in the [opts.headers](https://drachtio.org/api#srf-create-b2bua) option with whatever params you want.  However, to make sure that the drachtio server puts the proper IP address in there, just use the string 'localhost' for the host part, and it will get replaced.

i.e.
```js
srf.createB2BUA('sip:1234@10.10.100.1', req, res, {
   headers: {
      'Contact': '<sip:daveh@localhost>;param1=value;param2=value2'
   localSdpB: req.body
})..
```

**Comment by JimG777** [comment]
Hi, I will try that. Before, without 'localhost', it was adding a second Contact header. Same with To & From headers, it ends up just adding additional headers for them, when I would prefer to control the existing ones.

But, I would like to close this issue since I don't have much time to test and it isn't a high priority issue for us anymore. Thanks!
