### ISSUE TITLE
Inbound Calls

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-srf#16]
I would like to use drachtio-srf as an inbound sip/rtp server. Is there any sample configuration to drachtio register sip trunk with preferably rtpengine? If not is there any sample configration for fsmrf?

Thanks

**Comment by davehorton** [comment]
Yes, I have used it pretty extensively with rtpengine, using [this package I wrote](https://www.npmjs.com/package/rtpengine-client).

Here is a simple app that uses rtpengine: https://github.com/davehorton/drachtio-b2b-media-proxy

**Comment by salihy** [comment]
I implemented my outbound b2b-media-proxy with inspiration your project but when I implement inbound b2b-media-proxy i need to send register message to sip trunk in order to receive calls from trunk. Basically what i need is only a sample/documentation to send register message with credentials(login/password).

**Comment by davehorton** [comment]
Have a look at [srf.request](https://drachtio.org/api#srf-request).

In particular, note that you can provide the username and password, and it will automatically handle a digest challenge response for you.
