### ISSUE TITLE
outbundcall

### ISSUE THREAD

**Issue by falvarezoliva** [davehorton/drachtio-srf#18]
¿It´s posible to make and outbound call and on answer redirect to a registered user? The idea it´s implement a SIP CTI wrapper over drachtio based on nodejs.

**Comment by davehorton** [comment]
Not sure I follow what you want to do.  When you make an outbound call, you are sending an INVITE....the only way to truly redirect a call (if by redirect sending something like a 302 Moved) is when you are _receiving_ an INVITE, not sending it...

You can certainly make an outbound call and, on answer, put the called party on hold and then connect them to another user / endpoint (by sending a second INVITE).  Are you talking about something like that?

**Comment by davehorton** [comment]
I'm still not sure I understand what you want. 

From the asterisk documentation "The Asterisk Manager Interface (AMI) allows a client program to connect to an Asterisk instance and issue commands or read events over a TCP/IP stream"

This is exactly how drachtio-srf works: you connect to a drachtio server, receive an incoming call event and decide what to do with it.

Have you looked at any of the examples [here](https://drachtio.org/apps)?  Are any of them close to what you want to do?

Perhaps what you want is to use [outbound connections](https://drachtio.org/docs/developer-guide#advanced-topics), which lets you receive an inbound call via a web app and then decide which drachtio-srf app should handle it.

I could certainly provide an example if I understood what you wanted to do..
