### ISSUE TITLE
SIP & Provisional Response 181

### ISSUE THREAD

**Issue by haeferer** [davehorton/drachtio-srf#25]
Hi, 

We are making big steps forward using DrachtIO (great work!), and creating a TypeScript D.TS File for your libary. 
During our Test's we have seen some behaviour with our SIP Carrier (which is not a Bug with DrachtIO, but more a general question of SIP):

1. There is a Provisional Response 181 (Call Is Being Forwarded) defined on the SIP Protocol, but we havent seen this code in any of our calls (forwarded to mailbox, forwarded to other phone, etc.)
Is this Response not used, or does our carrier suppress this information?

2. If we dial a wrong number, the callflow looks like this
-> INVITE
<- TRYING
<- OK
<- AUDIO RTP Stream (20seconds, - Wrong number)
<- 404 Not Found
Is there a way to get the Information "404 - Number not found" without listening to the AudioStream for 20 Sec. before the final result arrives? 

thx for your help and inspiration

Andreas

**Comment by davehorton** [comment]
Hi there.  So glad you are having success with it, and I will appreciate any feedback / suggestions on how to make it better.

The 181 response is one that I don't think I have ever seen a carrier send back -- some may, but you definitely should not expect to see that from most carriers, it would be rare.

As far as the 404 Not Found, your message sequence above indicates the carrier answered the call (by sending 200 OK), but this must not be true if they later sent a 404 (only one final response is allowed).  So perhaps they established an early media session by sending a 183, played some audio ("this number is not valid" or something) and then sent a 404.  Is that what happened?

If that is the case, I agree that is not ideal at all.  I would open a ticket with the carrier on that, indicating you simply want to get the 404 response with no early media and see what they have to say about that.  And if they can't I would look for a new carrier, if that is an option for you.

**Comment by haeferer** [comment]
> played some audio ("this number is not valid" or something) and then sent a 404. Is that what happened?

Yup, thats exactly what happened.
we already asked the carrier about this behavior
* Early Media is required. An INVITE is not allowed without EARLY MEDIA (reason: for a live speaker the technical 404 is not enough, so there will always be a MediaStream to support REAL HUMANS to understand 404) 
* There is currently no technical way to overcome this "problem" (like sending an additional INFO Message). 
I understand, this is not a "real problem", cause it increases only the timespan before the SIPClient receives a 404. As far as i known with old PSTN (ISDN in germany) this behaviour was different. The Result (404) was send directly to the client and the audio was disconnected later.

**Comment by haeferer** [comment]
probably this is the only solution :(...

Thx for your time

**Comment by haeferer** [comment]
Oh, there is another technical info from our carrier. The "early media required" is needed, cause the FreeSwitch would need more different (more complex) configurations especially in combination with there GATEWAYS to Mobile and ISDN/PSTN on the other side...
