### ISSUE TITLE
Question - Can i use this framework to connect to any SIP server/provider ?

### ISSUE THREAD

**Issue by maheshmahadevan** [davehorton/drachtio-srf#26]

**Comment by davehorton** [comment]
Short answer: Yes.  

Of course, when sending to a commercial SIP provider you will need that provider to accept your calls, which usually means having an account established with them.  

Let me know if I can provide more specific guidance or direction on your specific implementation desires.

**Comment by maheshmahadevan** [comment]
@davehorton Thanks for your reply , i guess i just needed a sort of confirmation. I see your site has quite a few examples , let me get started with those and come back to you in case i am stuck somewhere.

**Comment by davehorton** [comment]
No, sorry.  drachtio-srf is specifically a module that connects to a drachtio server.  They are always used in combination.  So when I said you can send calls to any SIP provider, I mean the drachtios-srf plus drachtio server combo can work with any SIP server in terms of exchanging messages and setting up SIP dialogs.
