### ISSUE TITLE
Implementing a filtering proxy

### ISSUE THREAD

**Issue by Teyras** [davehorton/drachtio-srf#27]
Disclaimer: I'm not very well versed in SIP and maybe I'm asking an obvious question. In that case, I'm sorry.

I'm trying to make a simple proxy that forwards all invites to a SIP server using a paid account. However, the proxy should only allow whitelisted numbers. Relevant snippet of my code:

```
srf.on("connect", () => console.log("Connected!"));

srf.register((req, res) => {
        console.log("Incoming registration");
        srf.proxyRequest(req, `sip:${remoteHost}`)
});

srf.invite((req, res) => {
        console.log(`Calling ${req.calledNumber}`);

        if (config.whitelist.includes(req.calledNumber)) {
                srf.proxyRequest(req, `sip:${remoteHost}`)
        } else {
                res.send(486, "Busy");
        }   
});
```
The Drachtio server is running on port 5060.

When I run this, my phone (Cisco SPA-301) tries to register through my proxy (i see incoming request in Wireshark), but a response never arrives. Also, nothing gets printed from my node.js code besides "Connected!", so I suppose the request doesn't even arrive to the proxy. What might be the reason for this?

**Comment by davehorton** [comment]
I think the issue is that 'remoteHost' is not a variable - at least not in the code snippet you showed.

I'm assuming that you have configured the Cisco phone to have the drachtio server as an outbound proxy, so that the request-uri of the INVITE will have the ip address or dns name of the downstream SIP server that you want to proxy the requests to.  If that's the case, I would try this:

```
srf.on('connect', (err, hp) => {
  if (err) console.error(err, 'Error connecting');
  else console.log(`Connected, listening on ${hp}`);
});

function whitelist(req, res, next) {
  if (!config.whitelist.includes(req.calledNumber)) {
    res.send(403); // 403 Forbidden
  }
  next();
}

srf.register((req, res) => {
    console.log('Incoming registration');
    srf.proxyRequest(req, req.uri);
});

srf.use('invite', whitelist);
srf.invite((req, res) => {
  srf.proxyRequest(req, req.uri);
});
```
Try that and let me know if it works

**Comment by Teyras** [comment]
I only posted the relevant parts, `remoteHost` is actually picked from an env variable and I'm confident that this part of the code works. Anyway, I'm glad I don't need the variable since it can be replaced with `req.uri`.

To be clear, the Cisco phone has two config options, "Proxy" and "Outbound proxy". I configured the former to the upstream and the latter to my filtering proxy.

I made some progress by fixing my Docker setup - I didn't realize I have to explicitly forward UDP traffic to the Drachtio server. Now I can place calls, but incoming calls do not reach the phone.

**Comment by davehorton** [comment]
So now you are able to make an outbound call from your Cisco phone and have it proxied by the drachtio server out to your paid SIP server.  Is that correct?

And, assuming it is, you now want inbound calls from your paid SIP service provider to reach your Cisco phone, is that also correct?

**Comment by Teyras** [comment]
Exactly. As I said, I'm no expert in SIP, but I thought that registering with the upstream should be enough to receive incoming calls, even though the registration was proxied. What steps do I have to undertake to make it work?

**Comment by Teyras** [comment]
https://gist.github.com/Teyras/4020c5be1c7b3716a9e5a89da1cb9fa8 this is probably the best I can do. Also, I noticed that my invite handler caught the incoming call.

**Comment by davehorton** [comment]
A few things here.

First, it seems the SIP server is sending you an OPTIONS request after you proxy the REGISTER request, so it might be a good idea to add a handler for that.

```
srf.options((req, res) => res.send(200));
```

Secondly, if the SIP server is, in fact, sending the incoming INVITE to the drachtio server, that's good.  Most probably, you will need to handle this slightly differently than the outgoing INVITE -- you may need to proxy the INVITE to the Cisco by the source address and port it is sending from (`udp/[172.20.0.1]:46986` in your log) and not the address it put in the Contact header of the register (`10.6.26.128:5060`).

Can you show me another log, just like before, except after registering show the incoming INVITE when you make an inbound call?  I would need to see that to help further

**Comment by Teyras** [comment]
I added the OPTIONS handler and it made the Drachtio server crash after registration - like this: https://gist.github.com/8fa4d7b70fa17f90aea81e4cf0a09cf1. It seems that this only happened once though. The invite looks like this: https://gist.github.com/c4361713a3c1fe3e4eb719774d8aa6fe

I'm a little confused by the addresses in your response. `172.20.0.1` is almost certainly the Drachtio server (judging by the Docker prefix) and `10.6.26.128` is the LAN address of my phone.

**Comment by Teyras** [comment]
Yes, that's my public IP. It's probably worth noting that I'm planning to put the proxy on my VPS when it's finished, so it won't be in the same network as the phone. That might shake things up, right?

**Comment by davehorton** [comment]
OK, let's deal with the current situation first.

What you are going to have to do is distinguish between incoming calls and outgoing calls and treat them differently.
- Outgoing calls you are already handing -- you simply proxy them.
- Incoming calls you will need to look up the IP:port of the phone and proxy them there.

Here is how I would do it:
1.  Have a Map() which takes as key a phone number/extension and as the value the source IP and port of the device that registered that number.
2. When handling register requests, add an entry to the Map for the phone number found in the Contact header as key, and value `${req.source_address}:${req.source_port}`
3.  When handling an INVITE, check first if the host part of the request-uri is the domain of your SIP server.  If so, this is an outbound call, and proxy it as you are doing now.  If not, then retrieve the user part of the request uri and check to see if exists in your Map().  If it does, this is an incoming call, and proxy to the saved ip:port of the registering device.  And if not found in the Map(), then this should be an incoming call to a non-registered number, so you should simply return a 404.

I'd also suggest using this [middleware](https://www.npmjs.com/package/drachtio-mw-registration-parser) for register requests, as it will parse out the components of the Contact header and make it easier for you to get the registering phone number.

Let me know if any of this is not clear, or if you need help on creating the app.  I could probably put together an example app later this evening

**Comment by Teyras** [comment]
Wow, thanks for all the help you've given me, I really appreciate that! I'll probably get to hack on my app tomorrow - I'll report how it went.

**Comment by davehorton** [comment]
hmm, can I see a gist of the drachtio log again, showing the register and then the incoming invite?

**Comment by Teyras** [comment]
https://gist.github.com/49a8db01aa63b6d95a55444ed9ebabe1

**Comment by davehorton** [comment]
OK, the problem is here:
```
2019-01-26 13:33:03.971321 nta.c:8473 outgoing_try_tcp_instead() nta: INVITE (102) too large for UDP, trying TCP
```
the message is so large that the SIP stack tries to force the message TCP, which fails.

that threshold message size is configurable, since you are using docker please change it by adding a command-line arg `--mtu 1500`

see [here](https://drachtio.org/docs/drachtio-server#command-line-arguments) for details on command line arguments.

Also, just make the destination to send to "ip:port", without the "sip:" (though I should allow either, I will need to look into this)

**Comment by Teyras** [comment]
Wow, it works! Great! I noticed that when the caller hangs up before I pick up the phone, the phone keeps ringing. I suspect I need to forward some cancellation message, too?

**Comment by davehorton** [comment]
Hmm, no I think the CANCEL should have been automatically proxied onwards.  Can I see another log with that scenario?

**Comment by Teyras** [comment]
Huh, it looks like calls are not transmitted either (I can pick up the phone but voice is not transmitted)

**Comment by davehorton** [comment]
The media will (/should) travel a separate path - between your service provider's server and the phone.  Since the phone is nat'ed, this depends on your service provider supporting something called symmetric RTP, where the server sends to the source address:port it detects the media from the phone coming from, rather than the advertised address:port in the SDP of the INVITE, since that will be the natt'ed, private and unreachable address.

In any case, I suggest we first sort out the SIP signaling issue with the CANCEL, and then proceed to troubleshoot the audio issue after that

**Comment by Teyras** [comment]
Sorry for the long delay, my studies got in the way of my hobby projects. Anyways, here's a drachtio log caught when I hang up before picking up the VoIP phone and it keeps ringing: https://gist.github.com/Teyras/59e64e057f25f913f5813c4231618d69

**Comment by davehorton** [comment]
Hi there....sorry for my long delay on this.  Are you still interested in sorting this out?

It seems to me there is a bug on the Voip phone that is ringing, in that it does not respond properly to the CANCEL we send it.  What make / model of phone are you using?  Would you know the firmware version?

There may be something I can do on my side to adjust for this, let me know if you are still interested

**Comment by davehorton** [comment]
Is this still an issue?  Let me know if I should keep it open

**Comment by Teyras** [comment]
No, I don't think I need this anymore. Thanks for your help!
