### ISSUE TITLE
problem receiving cdr events 

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-srf#29]
Hi, 

I need to receive cdr:start and cdr:stop events but even though cdr:attempt and cdr:stop events received, start event does not receive, in my config file cdr config is '<cdrs>true</cdrs>', is there anything more i need to do? I also added drachtio.log file.

Thanks
[drachtio.zip](https://github.com/davehorton/drachtio-srf/files/2900122/drachtio.zip)

**Comment by davehorton** [comment]
I will look into this.  It seems like I may be only generating these currently in the proxy scenario....thought I had added them for B2B scenarios but it appears maybe not.  Will check and if necessary add these shortly

**Comment by davehorton** [comment]
Are you using the docker image or building from source?  I may want to have you something to test with

**Comment by salihy** [comment]
Hi, I built myself.

**Comment by davehorton** [comment]
I've created a branch called b2b-cdr in the drachtio-server project that should generate these events for B2B scenarios.  Could you build and test with that branch?  If it looks good I will merge it after your testing

**Comment by salihy** [comment]
Hi, thanks for quick response, i will check today and let you know.

**Comment by salihy** [comment]
Sorry for my late response, i just checked b2b-cdr branch and it works great, thanks for support.
