### ISSUE TITLE
Failed to find transport protocol upon a challenge (outbound proxy)

### ISSUE THREAD

**Issue by rhorning** [davehorton/drachtio-srf#38]
I'm trying to send a register using an outbound proxy.
The first register is sent successfully and it is responded with a challenge (401).
The issue is with the second register. Drachtio seems to successfully create the request, but it fails to send it to the outbound proxy, it does not find the transport protocol.
I changed the outbound proxy uri on the configuration to include the transport protocol, but it didn't work.

I increased the log level and noticed the difference on the log. The issue occurs around method SipTransport::findAppropriateTransport.
Only on the first request that the entire outbound-proxy parameter is passed to the mentioned method. In the second one, the transport is not on the uri.
Here are the parts of the logs comparing the first and the second request.
First request (SUCCESS):
```
SipDialogController::doSendRequestOutsideDialog sending request to route url: sip:21.21.100.190:5060;transport=tcp
SipTransport::findAppropriateTransport: searching for a transport to reach tcp/sip:21.21.100.190:5060;transport=tcp
SipTransport::findAppropriateTransport - after filtering for transport we have 1 candidates
SipTransport::findAppropriateTransport - after filtering for protocol we have 1 candidates
SipTransport::findAppropriateTransport: - returning the best match 0x564836faaa60: tcp/21.21.100.190:50060
```

Second request (FAIL):
```
SipDialogController::doSendRequestOutsideDialog sending request to route url: sip:21.21.100.190:5060
SipTransport::findAppropriateTransport: searching for a transport to reach udp/sip:21.21.100.190:5060
SipTransport::findAppropriateTransport - after filtering for transport we have 1 candidates
SipTransport::findAppropriateTransport - after filtering for protocol we have 0 candidates
SipTransport::findAppropriateTransport: - no transports found
```

I'm attaching the [Configuration file](https://github.com/davehorton/drachtio-srf/files/3248779/drachtio.conf.txt) and the [Log file](https://github.com/davehorton/drachtio-srf/files/3248763/drachtio.log).
Is there any missing configuration?
Let me know if you need anything else.

Thanks in advance!

**Comment by davehorton** [comment]
I think I see the issue.  Are you building from source, or using a Docker image?  If building from source, would you have the ability to test a fix that I make on a branch?

**Comment by rhorning** [comment]
Thanks for the response!
I can build it from source to test it.

**Comment by davehorton** [comment]
ok, test the `outbound-proxy-register-challenge-fix` branch of drachtio-server with your existing code and config., and post the results here.

**Comment by rhorning** [comment]
It worked! The second register is successfully sent!
