### ISSUE TITLE
Bug/documentation mistake: cbRequest not providing request object in first response value

### ISSUE THREAD

**Issue by WhiteyDude** [davehorton/drachtio-srf#41]
Hi Dave,

Testing out cbRequest on a `createUAC` call doesn't appear to yield any result, just a null value:

```javascript
 srf.createUAC(`sip:${outbound_endpoints[key]}@dummy.host`,
  {
    localSdp: b_endpoint.local.sdp,
    headers: b_outbound_headers
  },
  {
    cbRequest: (req) => console.log(`Received request - ${req}`),
    cbProvisional: (res) => console.log(`got provisional response: ${res.status}`)
  }
)
```

With this in place, my console outputs:

> 0|app    | Received request - null
> 0|app    | got provisional response: 187

Some digging into the code (http://davehorton.github.io/drachtio-srf/api/srf.js.html#line250) shows me the function returns null,obj instead of just the obj. Given cbProvisional only returns the obj, I'm unsure if this is a documentation mistake or not.

The following docs mislead this:

https://drachtio.org/docs ("Canceling an INVITE we sent")
http://davehorton.github.io/drachtio-srf/api/Srf.html#~uacProgressCallbacks

Cheers!

**Comment by davehorton** [comment]
Docs are wrong. Signature is (err, req)

**Comment by davehorton** [comment]
fixed in upcoming docs release

**Comment by davehorton** [comment]
fixed, many thanks for pointing this out!

**Comment by spointer** [comment]
Hi,
The following doc needs to be fixed, too.

https://drachtio.org/api#srf-create-uac

**Comment by davehorton** [comment]
thanks!  Just committed a fix, will push later today
