### ISSUE TITLE
B2BUA problem.

### ISSUE THREAD

**Issue by phildunks** [davehorton/drachtio-srf#42]
Hi Dave

I'm having an issue getting the basic createB2BUA example working.

Running it as shown in the documentation causes a validation error, which on inspection is because the signature has changed to have the URI in index 2 rather than index 0?

After moving it, I now see log message 'Error creating UAS dialog: SipError: Sip non-success response: 503'.

No INVITE is sent to my UAS, and a 503 Service Unavailable is returned to my UAC.

The version in my package.json shows     "drachtio-srf": "^4.4.8"

Thanks for any advice.

Phil

**Comment by davehorton** [comment]
Sorry for the docs issue.  Can you upload a gist of the drachtio server log?  My guess at this point is that the outbound INVITE to your UAS is going to an ip:port where no device is listening, and the sip stack is responding to that udp error by generating a 503.  But it would be good  to see the log, if possible.

Meanwhile I will fix the docs issue. (Note: the method signatures themselves on the [api page](https://drachtio.org/api#srf-create-b2bua) are correct and up to date)

**Comment by phildunks** [comment]
Hi Dave

https://gist.github.com/phildunks/931000be8916ee88bfa859982e4aed14

The sipp UAS is listening on port 5063.
If I point my sipp UAC at it, it gets the call ok.
Thanks
Phil

**Comment by davehorton** [comment]
For some reason it is attempting a tcp connection on the outbound, which fails

```
2019-06-24 11:41:24.639342 nta.c:8662 outgoing_print_tport_error() nta: INVITE (6134450): Connection refused (111) with tcp/[192.168.47.161]:5063
```
I'm not totally sure why that is.  What version of drachtio are you running (`drachtio -v` will tell you)?
Are you running a docker image or a source build?

**Comment by phildunks** [comment]
In Docker, but in a mac. I'm starting it as follows.

docker run -d --rm --name drachtio -p 5060:5060/udp  -p 9022:9022/udp  -p 5060:5060/tcp  -p 9022:9022/tcp     drachtio/drachtio-server drachtio --contact "sip:*;transport=tcp,udp"

**Comment by phildunks** [comment]
Version v0.8.2-1-ga65722fcb

**Comment by davehorton** [comment]
Try changing the order of protocols in the command line to udp first, ie --contact "sip:*;transport=udp,tcp"

This will most probably fix your issue, but should not be required, so I will look into this further.  (I'd suggest testing with the latest docker image, but docker.io seems to be down right now)

**Comment by phildunks** [comment]
Yes, Dave, that's fixed it.
Thanks very much for the very fast response.
All the best,
Phil
