### ISSUE TITLE
Auth digest responses get proxied to udp irrespective of original uri transport

### ISSUE THREAD

**Issue by rjp44** [davehorton/drachtio-srf#45]
When a 401 auth challenge is received for a request (e.g. REGISTER) sent using TCP or TLS transports, the response reply is always proxied to `sip:<ip_address>:<port>` on the default UDP transport which breaks the exchange.
This is caused by the code around line 107 of digest-client.js which is trying to avoid new DNS lookups but in doing loses critical elements of the original uri.
Have a proto-fix, will test and submit a PR shortly.

**Comment by davehorton** [comment]
Thank you!  will push this in a release today or tomorrow
