### ISSUE TITLE
CANCEL not being forwarded across B2BUA

### ISSUE THREAD

**Issue by danieludy** [davehorton/drachtio-srf#47]
Issue is that in some attempts if the A leg sends a CANCEL into drachtio that CANCEL is not forwarded to the B leg.
Redacted log being sent over email...

**Comment by davehorton** [comment]
ok from the trace you sent me it looks like this:
```
A --INVITE--> B2B --INVITE--> B
A <-- 100 ---- B2B
                          B2B <-- 180 ----B
A <-- 180 -----B2B

..25 secs pass..

A --CANCEL --> B2B
A <-OK cancel--B2B
A <-487 invite--B2B
A --ACK-------->B2B

and then no CANCEL is sent on the B leg.  Is that correct?

I will try to recreate, but is there any other hints or thoughts you can give me about how to recreate ?

How easily is this recreateable?  Is it possible to recreate in a test environment with `DEBUG=drachtio:srf node <your app>` and get those drachtio-srf debug logs?

**Comment by danieludy** [comment]
Yes that is what we are seeing... I have not been able to reproduce outside
of a decent amount of load (more than I can easily make happen manually).
I will see what it would take to get those debug logs enabled on all the
hosts to capture that info...

**Comment by davehorton** [comment]
also, from the logs it looks like you are using outbound connections, is that right?  I will try to construct a load test of my own to recreate, and want to make sure I set up in a similar way.  Your app is using `Srf#createB2BUA` to create the outbound call?

**Comment by davehorton** [comment]
I do see something interesting in your log.  The CANCEL we got from A was this:

```
<182>Jul 17 19:40:28 ip-10-0-57-131 recv 591 bytes from udp/[10.0.12.10]:5060 at 19:40:28.425238:
CANCEL sip:+TO_NUMBER@TO_HOST SIP/2.0
From: sip:+FROM_NUMBER@127.0.0.1;tag=8f81325d-21f8-4f82-8386-5471159ae1cb
To: sip:+TO_NUMBER@TO_HOST
Call-ID: 00e2d40c-a6c8-4454-8da6-0e9e9bddb2e3
CSeq: 4846 CANCEL
Content-Length: 0
```

that;'s the one we respond to with 200 OK to the CANCEL and 487 to the INVITE, but don't send the CANCEL on the B leg.

Some time later, the drachtio server gets this 500 Internal Server error from the client for what looks like the same A leg, and then bounces the client.  This implies there was a javascript exception of some kind in the app:

```
<183>Jul 17 19:40:43 ip-10-0-57-131 Client::read_handler read: fa7792b5-77b4-40be-96f8-93806307a5b8|sip|cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0|
SIP/2.0 500 Server Internal Error
Call-ID: 00e2d40c-a6c8-4454-8da6-0e9e9bddb2e3
cseq: 4846 INVITE
from: sip:+FROM_NUMBER@127.0.0.1;tag=8f81325d-21f8-4f82-8386-5471159ae1cb
to: sip:+TO_NUMBER@TO_HOST
Content-Length: 0
<183>Jul 17 19:40:43 ip-10-0-57-131 Client::processMessage - got request with 4 tokens
<183>Jul 17 19:40:43 ip-10-0-57-131 Client::processMessage - request id fa7792b5-77b4-40be-96f8-93806307a5b8, request type: sip transaction id: cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0, dialog id:
<183>Jul 17 19:40:43 ip-10-0-57-131 ClientController::addApiRequest: clientMsgId fa7792b5-77b4-40be-96f8-93806307a5b8; size: 1
<183>Jul 17 19:40:43 ip-10-0-57-131 SipDialogController::doRespondToSipRequest thread 139805243521088
<183>Jul 17 19:40:43 ip-10-0-57-131 SipDialogController::findAndRemoveTransactionIdForIncomingRequest - searching transactionId cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0
<183>Jul 17 19:40:43 ip-10-0-57-131 SipDialogController::findAndRemoveTransactionIdForIncomingRequest - failed to find transactionId cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0, most likely this is a response to an invite we sent
<178>Jul 17 19:40:43 ip-10-0-57-131 SipDialogController::doRespondToSipRequest - unable to find irq or iip for transaction id cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0
<183>Jul 17 19:40:43 ip-10-0-57-131 ClientController::removeApiRequest: clientMsgId fa7792b5-77b4-40be-96f8-93806307a5b8; size: 0
<183>Jul 17 19:40:43 ip-10-0-57-131 ClientController::removeNetTransaction: transactionId cd637f09-0fff-4458-a3ec-8dbeb5c8a3d0; size: 3
<183>Jul 17 19:40:43 ip-10-0-57-131 Client::write_handler - wrote 135 bytes: system:0
<178>Jul 17 19:40:43 ip-10-0-57-131 Client::read_handler - bouncing client due to error reading: asio.misc:2
```

You should have seen an exception burped up on the app...any chance you saw that?

**Comment by danieludy** [comment]
Yes to all... I enabled the debug logging in the srf last night, have not
been able to check if we captured the issue or not yet but will let you
know as soon as I do.

**Comment by danieludy** [comment]
Sorry, didn't see your second comment... Yes we saw the 500, but that was because we tried to send the 200 from the B leg to the A leg and the transaction didn't exist... So not the cause of the issue not sending the CANCEL in the first place...

**Comment by davehorton** [comment]
OK will try to recreate in a load test of my own.  Meanwhile do let me know if you happen to capture any logs of this with debug logging set

**Comment by danieludy** [comment]
Have a bit more info on this one...
The missing CANCEL from SRF has been found, it is being send to a different drachtio server instance...

> <183>Jul 17 19:40:28 ip-10-0-44-3 Client::read_handler read: 35745a49-26d0-4582-94b8-591c2e320045|sip|400b7701-1bd6-48aa-874b-c46963bfa48d|
CANCEL sip:+TO_NUMBER@DESTINATION_HOST SIP/2.0
Content-Length: 0
<183>Jul 17 19:40:28 ip-10-0-44-3 Client::processMessage - got request with 4 tokens
<183>Jul 17 19:40:28 ip-10-0-44-3 Client::processMessage - request id 35745a49-26d0-4582-94b8-591c2e320045, request type: sip transaction id: 400b7701-1bd6-48aa-874b-c46963bfa48d, dialog id:
<183>Jul 17 19:40:28 ip-10-0-44-3 Client::processMessage - sending a CANCEL request inside a transaction
<183>Jul 17 19:40:28 ip-10-0-44-3 ClientController::addApiRequest: clientMsgId 35745a49-26d0-4582-94b8-591c2e320045; size: 1
<178>Jul 17 19:40:28 ip-10-0-44-3 SipDialogController::doSendCancelRequest - unknown transaction id 400b7701-1bd6-48aa-874b-c46963bfa48d
<183>Jul 17 19:40:28 ip-10-0-44-3 ClientController::removeApiRequest: clientMsgId 35745a49-26d0-4582-94b8-591c2e320045; size: 0

One thing to note that I only found this because I was looking at a different issue and had a packet trace running. I have a TCP session for a connection to an SRF node app initiated by Drachtio server for an invite. I saw where in that TCP session drachtio server was sent a CANCEL from SRF for a totally different call (that was set up and managed by a different TCP session). It appears that the SRF is confusing which TCP session to send the CANCEL to the B leg over.

I can't attach the trace here, but will see if I can get it scrubbed to be able to send to you over email.

**Comment by danieludy** [comment]
If it wasn't clear in the above message the node app can and does have multiple TCP sessions from multiple drachtio servers at any given time...

**Comment by davehorton** [comment]
Thanks, that is really useful information.   I will have a look at the code relating to this.

**Comment by davehorton** [comment]
I have an idea of what the bug might be.  I have to try to recreate it in a test environment first and then apply the fix.

**Comment by davehorton** [comment]
ok this is fixed in drachtio-srf@4.4.12.  Can you retest and close this issue if your results are satisfactory?

**Comment by davehorton** [comment]
can you confirm your issue is now resolved?

**Comment by davehorton** [comment]
closed due to lack of response (hopefully fixed with reference commit)
