### ISSUE TITLE
Publish Support

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-srf#5]
Hi,

I am trying to create some internal testing tools using Drachtio. I am using drachtio-srf to act as a registrar and create a proxy for invite/sessions. I would also like to handle publish methods directly. When I call srf.publish(), Node complains that it doesn't exist. The method support comes from sip-methods so I added PUBLISH to the exported array. However, even now the method doesn't fire. Can you point me to a solution? Does the drachtio-server pass it through? I am using server version 0.5.0-122-g3a17efc.

Thank you!

**Comment by JimG777** [comment]
Hi,

I found a workaround at least for my purposes. In drachtio-server, DrachtioController::processMessageStatelessly(), if I add sip_method_publish as a case to the first group of cases in the switch, the PUBLISH gets to the drachtio-srf client. I am not yet familiar with the codebase yet but it appears to be safe (again, for my purposes).

Also, as mentioned in the OP, I had to modify sip-methods too in order to create a handler for publish. Please note, in the top-level node_modules directory, there is a sip-methods project. Then, it is ALSO in the drachtio-srf/node_modules directory, and they are currently out of sync anyway (0.1.0 and 0.2.0 respectively).

Thanks

**Comment by davehorton** [comment]
Sounds good. If you feel like making a PR for this fix please go ahead. (Preferably on the cluster-experimental branch)

**Comment by davehorton** [comment]
I pushed a commit for this to drachtio-server on the cluster-experimental branch.  (That will build drachtio/drachtio-server:latest on dockerhub)

**Comment by JimG777** [comment]
Thank you Dave. There is an issue with proxy handling in the cluster-experimental branch and I will post a comment in drachtio-server repo for it.
