### ISSUE TITLE
Access to req.socket

### ISSUE THREAD

**Issue by jonastelzio** [davehorton/drachtio-srf#51]
Hey there!

So, I'm relying on the IP of the drachtio instance that connects to my SRF instances (outbound), and while the documentation doesn't have any information on it, there is the socket-object on the request object which seems to basically just be the node socket associated with the request.

Is there a more correct way to obtain the drachtio servers ip, or is it perfectly fine to use that - my main concern would obviously be that this variable were to disappear in the future. Maybe a getSocket() method to provide a proper interface for obtaining the socket?

Here's what I'm currently doing:
```
srf.use((req, res, next) => {
    var drachtioServerIp = req.socket.remoteAddress;
    req.drachtioServerIp = drachtioServerIp;

    next();
});
```

**Comment by davehorton** [comment]
I agree more is needed here.  Do you want to retrieve the SIP addresses, ports, and protocols that the remote drachtio server is listening on?  Or just the IP address that it is using when it makes the tcp connection with the app?

It seems like I should add some public methods (or getters) to the req object

**Comment by davehorton** [comment]
I'm thinking that I could simply provide attributes on the req object like
```
srf.invite((req, res) => {
   console.log(`server address: ${req.server.address}`);
   console.log(`server is listening on ${req.server.hostport)`)
   ..
});
```
i.e similar hostport info that you can get in the `connect` event when you make an inbound connection to the drachtio server.  Thoughts

**Comment by jonastelzio** [comment]
I think the req.server approach is great, since it matches what's on the inbound data.

Generally I think as much data should be made available as possible. All SIP related data on the connection could be extremely useful in some scenarios actually, so that would be very cool.

I don't know if it's possible, but as we talked about with Application Load Balancers in front of Drachtio-server, would it be possible to get access to certain HTTP Headers from the websocket established to SipSofia, or is Sofia keeping those too tight to make that viable? I'm thinking in particular about stuff like Cookie, Authorization, X-Forwarded-For headers.

This information would also be absurdly nice to have in the HTTP Request made by drachtio as well. Especially the clients real IP address (for security purposes).

**Comment by davehorton** [comment]
ok this was added in drachtio-srf@4.4.14.  The following attributes are available on the `req` object:

```
req.server.address - the IP address the drachtio server uses when it connects to the app
req.server.hostport - the IP addresses the drachtio server is listening on for sip
```

**Comment by davehorton** [comment]
can you open two new issues for the other features you requested:
- drachtio server to respond 200 OK to a health check from an AWS load balancer
- drachtio server to make HTTP headers from incoming ws connections available to routing callback
```
