### ISSUE TITLE
Header Case Sensitivity

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-srf#6]
Hi,

Case sensitivity is generally benign in SIP, but I would like consistent case in my headers for testing. It seems like all headers that are 'normal' or generated automatically are formatted like 'Contact', 'To', 'Content-Length' with upper case first letters. When I add custom headers, they are always set to lower case. Is there a way to have the header on-the-wire match the case that is provided in the header API? For example:

```
srf.register(req, res) => {
  res.send(200, {
    headers: {
      expires: 3600,
      'SIP-ETag': 'something'
    }
  });
});
```

In this case, expires goes out on the wire as 'Expires' but the SIP-ETag is 'sip-etag'.

Thanks,

James

**Comment by davehorton** [comment]
when you get a chance, can you retest this with the latest drachtio-server?  There was a related issue where SIP-Etag was not being handled properly.

**Comment by JimG777** [comment]
Hi, SIP-ETag looks good now.
