### ISSUE TITLE
FEATURE REQUEST: Destination IP available through framework

### ISSUE THREAD

**Issue by amoonrah** [davehorton/drachtio-srf#65]
if the drachtio server is binding to multiple IPs, can the IP that received the request be made available available in the req object?

**Comment by davehorton** [comment]
yes, check this:

https://github.com/davehorton/drachtio-srf/issues/51

**Comment by amoonrah** [comment]
Hi,

that's not the same, I'm looking for the destination IP the SIP request lands on, 

so if my drachtio server is listening on ip 1.1.1.1:5060 and 2.2.2.2:5060 for sip message, I need a variable that tells me which IP address the INVITE message landed on.

the one you issue above always lists the IP address that the app connected to and not the IP address the invite came in on.

**Comment by davehorton** [comment]
ah, ok.

**Comment by amoonrah** [comment]
will this require changes on the server side or is that information already available and just needs to be populated into the req object?

**Comment by davehorton** [comment]
changes will be needed on server side as well

**Comment by davehorton** [comment]
this feature has been added.  To access it you need to be running

drachtio-server >= v0.8.4-rc4
drachtio-srf >= 4.4.22

When running a compatible release combination, the `req` object for a new request outside of a dialog will have a `receivedOn` property that provides the local sip endpoint (as ip:port) that handled the incoming request, e.g.

```
srf.invite((req, res) => {
   console.log(`request received on ${req.receivedOn}`);
```

**Comment by amoonrah** [comment]
greatly appreciated, I will compile and test.

**Comment by amoonrah** [comment]
works :)

**Comment by amoonrah** [comment]
great work 👍
