### ISSUE TITLE
possible bug: register request does not contain contact header

### ISSUE THREAD

**Issue by amoonrah** [davehorton/drachtio-srf#66]
If I create a register request, if I don't provide a contact header, the header is not created.

is that a bug or by design?

function register(configs) {

   srf.request(`sip:${configs.domain}`, {
      method: 'REGISTER',
      proxy: `sip:${configs.proxy}`,
      headers: {
         'From' : `sip:${configs.from}@${configs.domain}`,
         'To' : `sip:${configs.from}@${configs.domain}`,
         'Contact' : `sip:${configs.sourceip}`,
         'Expire': 600 },
      auth: {
         username: configs.username,
         password: configs.password }
   }, (err, req) => {
      if (err) return console.log(`Error sending Register: ${err}`);
         req.on('response', (res) => {
         console.log(`\nREGISTER request for ${configs.service} using account ${configs.from}`);
         console.log(`REGISTER response for ${configs.service} using account ${configs.from} : ${res.status} ${res.reason}`);
      });
   });

**Comment by davehorton** [comment]
By design.  The Contact header is a key part of the REGISTER request, and we can not figure out for you what it should be.

**Comment by amoonrah** [comment]
what variable contains the source IP that drachtio will use to send the message?

**Comment by davehorton** [comment]
If you mean what ip address should you put in the Contact header, just put the string 'localhost' and the drachtio server will replace that with the sending address before actually sending the message

**Comment by amoonrah** [comment]
localhost will not be taken from the hosts file?

**Comment by davehorton** [comment]
no, it is just a token that the drachtio server looks for and replaces in requests sent by an application
