### ISSUE TITLE
Proxying UDP to TCP

### ISSUE THREAD

**Issue by kiyose** [davehorton/drachtio-srf#69]
I am looking for way to proxy an INVITE message between two environments. 

I need to listen for an INVITE on UDP, add a VIA header indicating which environment the invite came in on and then relay the message over TCP. 

This is specifically to utilize the AWS endpoint service (privatelink) pattern which will not support UDP. 

Messages returning to the originating server will need to do the reverse. I.e. TCP -> UDP and also remove our VIA header.

**Comment by davehorton** [comment]
This should do the trick:
>Note: replace the IP addresses of the drachtio server and the remote host to proxy to as appropriate.
> Note: In the example below I'm adding a Record-Route header.  If you don't want a Record-Route header added, just remove that whole `opts` param (described in detail here [here](https://drachtio.org/api#srf-proxy-request))
```
const Srf = require('drachtio-srf');
const srf = new Srf();

srf.connect({
  host: '127.0.0.1',
  port: 9022,
  secret: 'cymru'
})
  .on('connect', (err, hp) => console.log(`connected to drachtio server listening on ${hp}`))
  .on('error', (err) => console.log(`Error connecting ${err.message}`));

srf.invite(async(req, res) => {
  try {
    const result = await srf.proxyRequest(req, 'sip:127.0.0.1:5062;transport=tcp', {
      recordRoute: true
    });
    console.log(`proxy result: ${JSON.stringify(result)}`);
  }
  catch (err) {
    console.log(err, 'Error proxy request');
  }
});
```
