### ISSUE TITLE
Proxy with modified callingNumber/calledNumber

### ISSUE THREAD

**Issue by enp** [davehorton/drachtio-srf#72]
Is it possible to proxy requests to source address back with modified callingNumber/calledNumber? Tried to do so with:

```
srf.invite((req, res) => {
  console.log(req.headers)
  console.log(`${req.callingNumber} => ${req.calledNumber}`)}})
  srf.proxyRequest(req, req.source_address, {
    callingNumber: '+78630000001',
    calledNumber: '+78630000002'
  }).then((result) => {
    console.log(JSON.stringify(result));
  });
})
```

but without success ... Maybe another way exists?

**Comment by davehorton** [comment]
Proxying back to the source?  That's an interesting use case....not sure what you are trying to do, but more typically people might use a 302 redirect if the idea is to change the destination number.

Anyways, not sure this will work, but you might try explicitly setting to and from headers
```
srf.proxyRequest(req, req.source_address, {headers: {from: 'xxxx', to: 'xxx'}}..
```
Again not sure this would work but maybe try

**Comment by enp** [comment]
Thank you, explicitly setting to and from headers works, but looks like I need to modify number in request line with outgoing INVITE too - how to do it?

**Comment by enp** [comment]
As for 302 redirect (or REFER) - I need to modify calling number too, is it possible?

**Comment by davehorton** [comment]
302 would not change the calling number.

You should be able to change the destination number on the proxy by putting the new destination in the uri:

```
srf.proxyRequest(req, `sip:1234@${req.source_address}`, {headers...
```

**Comment by enp** [comment]
Putting the new destination into uri works good in test environment with sipp and doesn't work in real network (maybe because initial INVITE from network contain literal trunk name instead of source ip address in request line?)
Maybe I can set request line of request directly?

**Comment by enp** [comment]
Tried to add debug output to proxy functions in node_modules/drachtio-srf/lib/{request,drachtio-agent}.js but I see my uri `sip:1234@${req.source_address}` everywhere which is not the same as request line in outgoing INVITE. Can you point me place of drachtio-srf code where outgoing INVITE goes outside?

**Comment by davehorton** [comment]
can you run the drachtio server at debug level and capture / show the logs for the proxy attempt?

**Comment by enp** [comment]
I see something like this in drachtio server log:
```
2019-12-28 21:01:04.669873 Client::processMessage - received proxy request e4f262ef-3987-4449-93c1-48d76abee098,proxy,9f981235-91ae-4186-a5c3-e7bcc935a6aa,rem
ainInDialog,fullResponse,followRedirects,serial,,,sip:+78630000002@10.0.0.1
...
2019-12-28 21:01:04.671455 isLocalSipUri: checking to see if this is one of mine: sip:+78630000001@TESTPLA0;user=phone
...
2019-12-28 21:01:04.674993 makeTags - Adding well-known header 'to' with value 'sip:+78630000002@10.0.0.1'
2019-12-28 21:01:04.675441 send 1376 bytes to udp/[10.0.0.1]:5060 at 21:01:04.675184:
INVITE sip:+78630000001@TESTPLA0;user=phone SIP/2.0
...
To: <sip:+78630000002@10.0.0.1>
```
Request line with TESTPLA0 was in initial INVITE, so you going to say that drachtio server can send only same request line in re-INVITE as it was in initial INVITE and I can't change this behaviour via drachtio-srf?

**Comment by enp** [comment]
Maybe simple way to see exchange between drachtio server and drachtio-srf as text exist to ensure?

**Comment by davehorton** [comment]
this line is key
```
checking to see if this is one of mine: sip:+78630000001@TESTPLA0;user=phone
```
the only scenario where the server will let you substitute a new uri is if it finds that the initial incoming invite was targeted to the server itself.

In this case, since it does think TESTPLA0 refers to the local server, it will not change the uri.

**Comment by enp** [comment]
Why server doesn't think that TESTPLA0 refers to it? Maybe it is possible to refer in some way? Tried to refer via /etc/hosts but without success ...

**Comment by enp** [comment]
Looks like srf.createB2BUA is more suitable for my case than srf.proxyRequest, why you did not say me about that? :)

Can you advice me right way to modify callingNumber on B leg for createB2BUA?

**Comment by enp** [comment]
Changed callingNumber via opts.headers.from in the same way as I tried with srf.proxyRequest, so problem is completely solved :)
