### ISSUE TITLE
Duplicate Contact headers in responses on B2BUA

### ISSUE THREAD

**Issue by havfo** [davehorton/drachtio-srf#76]
When I specify in `createB2BUA` ...:
```javascript
responseHeaders : { contact : '<validcontact>' }
```
... this happens in the provisional, and final responses to UAS:
```
100 -> No contact
180 -> 1 contact
180 -> 2 contacts
180 -> 3 contacts
183 -> 4 contacts
200 -> 5 contacts
```

This happens on both lowercase`contact`, and camelcase `Contact`.

**Comment by davehorton** [comment]
fixed in 4.4.31

**Comment by havfo** [comment]
This seems to not be fixed. On e.g. the second provisional response the command sent to drachtio-server is:
`makeTags - Adding well-known header 'contact' with value '<validcontact>,<validcontact>'`
which turn into two duplicates.

(Note, I am running the patched server version from https://github.com/davehorton/drachtio-server/issues/114 if that matters)

**Comment by davehorton** [comment]
hmm, can you show me the drachtio server log at debug

**Comment by havfo** [comment]
Sent you unfiltered on mail.

**Comment by havfo** [comment]
You can see how I use it here: https://github.com/havfo/drachtio-msteams-gw/blob/9ea98298e46dc5b97821efb153518dd7d9f6eaeb/lib/handlers/Session.js#L140

**Comment by davehorton** [comment]
You probably do not want to include a Contact on a provisional response, unless it is a reliable provisional response.  To support this, `opts.responseHeaders` can be function that returns an object.  The function will be called like so:

```
`responseHeaders: (uacRes, headers) => {...
```
where you are passed the provisional response object, as well as any headers that have already been copied from the B leg to the A leg (via `opts.proxyResponseHeaders`).  This would let you examine `uasRes.status` and only put a Contact header on your response if it was a 200 OK.

This is not related to the bug but may be useful to you

**Comment by havfo** [comment]
Ah, great, I must have missed that on my many rounds through the API documentation :smile:
