### ISSUE TITLE
npm Deployment Issue

### ISSUE THREAD

**Issue by JimG777** [davehorton/drachtio-srf#9]
Hi, I am trying to get npm to update with the latest version of drachtio and drachtio-srf so that it references the sip-methods 0.3.0 version. But even when we update the develop branches here, it doesn't update. Also, the latest develop version here is 4.2.1, but npm has it as 4.2.4. Can you possibly sync-up the versions? I would like to deploy some tests automatically, but can't without publish support. Thanks!

**Comment by davehorton** [comment]
Yes, I plan to get all of this sorted out this weekend, with some major changes to drachtio-srf that I will be checking in

**Comment by JimG777** [comment]
Thank you very much.
