### ISSUE TITLE
Retrieve SDP from ACK (reInvite without SDP)

### ISSUE THREAD

**Issue by rhorning** [davehorton/drachtio-srf#91]
Hello, @davehorton.

Is it possible to retrieve an SDP from an ACK?
Imagine 2 peers in an established dialog, where Peer 1 is handled by Drachtio and Peer 2 is a SIP phone. Peer 2 sends a reInvite without SDP:

**Peer 2** sends INVITE without SDP to **Peer 1**
**Peer 1** responds 200 OK with SDP to **Peer 2**
**Peer 2** sends ACK with SDP to **Peer 1** 

How can we retrieve the SDP coming on Peer 2's ACK?
Celso has opened issue 60 in order to send an SDP on ACK, I believe this would be the complement for that.

**Comment by spointer** [comment]
I think you can get the modify event from Peer 1 dialog and you can call res.send with 200 OK.
As you can see from this link(https://drachtio.org/api#sip-response-send), send function has optional fnAck function and you can get the sdp body from this callback function.

**Comment by davehorton** [comment]
That's exactly right!  Something like this should work:
```
// assume we have a SipDialog from createUAC/UAS/B2BUA..
dlg.on('modify', (req, res) => {
  console.log('got reinvite');
  res.send(200, {
    localSdp: 'v=0...',
  }, (ack) => {
     // ack is a SipRequest
     console.log(`got ACK with body ${ack.body}`);
  }
});
```

**Comment by rhorning** [comment]
Thanks, @davehorton and @spointer!
I'll try and let you know!

**Comment by rhorning** [comment]
It worked!
I just needed to insert another parameter before the ACK callback:
`  res.send(200, {opts}, null, (ack) => {
     console.log('got ACK with body ${ack.body}');
  });`

The first callback is called when the response is sent, the second one contains the ACK.

@davehorton, you can close it. 
Thanks!
