### ISSUE TITLE
Re-inviting calls dropped by FreeSWITCH

### ISSUE THREAD

**Issue by IdlePhysicist** [davehorton/drachtio-srf#96]
This is not an issue, but rather a request for advice.

Our test system consists of one Drachtio pod (v0.8.6-rc2 at present) which proxies traffic to two FreeSWITCH pods. This system is in a Kubernetes cluster. We currently use Drachtio as a proxy to route traffic to the FreeSWITCH pods.

To recover from a failed FreeSWITCH pod we would like to send re-invite messages to both ends of the dropped calls to reconstitute the calls of a fresh FreeSWITCH pod.

What is the optimal way to do this using the Drachtio SRF library?

**Comment by davehorton** [comment]
If your drachtio app is a proxy, there is no way to do this; i.e proxy can not initiate its own re-INVITE.

If your app is a B2BUA, then you would:
- send an INVITE with no SDP to new freeswitch
- take the SDP returned in the 200 OK and reINVITE the A leg
- take the SDP returned from that leg and include it in the ACK to freeswitch
