### ISSUE TITLE
Support for OpenSIPs or Kamailio

### ISSUE THREAD

**Issue by sido420** [davehorton/drachtio-srf#97]
I am new to VoIP and still learning.

I have a requirement to handle SIP calls through a nodejs server.

I wanted to know if its possible to use drachtio-srf with any other SIP server than drachtio.

If yes, whats the benefit of using Drachtio server over Kamailio etc then?

**Comment by davehorton** [comment]
No, drachtio-srf works specifically with the drachtio server.

My sense is that the people who choose to work with drachtio do so because they are familiar with & prefer writing applications in Node.js, as opposed to learning the unique configuration file syntax of the other products you mention

**Comment by sido420** [comment]
The question then is: Is Drachtio server as stable, scalable, and feature rich as OpenSIPs or Kamailio? 

Can Drachtio server itself work as proxy for Kamailio/OpenSIPS?

**Comment by davehorton** [comment]
- feature rich?  Totally depends on what features are important to you
- stable?  Hmm, drachtio is much earlier in its development than those products, which have each been around > 10 years.  I would guess they are more stable. 
- scalable? No.  Both opensips and kamailio can scale to greater numbers of calls on a single server, assuming that is your measure.  You can think of drachtio server as handling hundreds of incoming calls per second on an quad core VM, opensips/Kamailio as handling thousands of calls per second.  That said, I have deployed at fairly massive scale using horizontal scaling
- proxy to kamailio/opensips: yes, you can build a proxy application to anything using drachtio.

However, positioning drachtio as a proxy to Kamailio/openSIPs would probably not be a common thing -- more likely the other way around, or only drachtio.

The value of drachtio is to allow you to build many kinds of SIP applications -- not just proxies.  If you are looking for a proxy only, then that is exactly what Kamailio is good for and is typically used for.  Bit of a learning curve, in my opinion, but good product so if you have time to invest and you simply want a proxy, I would recommend you go that route.  People that use drachtio are typically building SIP server applications that involve more application logic, including such things as webrtc signaling/media proxies, back to back user agents, siprec recording applications, etc.
